// Export all email templates
export { BaseLayout } from './base-layout'
export { WelcomeEmail } from './welcome'
export { BookingConfirmationEmail } from './booking-confirmation'
export { BookingReminderEmail } from './booking-reminder'
export { PaymentSuccessEmail } from './payment-success'
export { PaymentFailedEmail } from './payment-failed'
export { ApplicationSubmittedEmail } from './application-submitted'
export { ApplicationApprovedEmail } from './application-approved'
export { ApplicationRejectedEmail } from './application-rejected'
export { ContactFormEmail } from './contact-form'
export { PasswordResetEmail } from './password-reset'
